module Scientific_Subroutine_Package
implicit none
private

public ::  &
absnt,  acfi,    ahi,    ali,    apch,   apfs,   apll,   apmm,   arat,   array,  &
ateig,  atse,    atsg,   atsm,   auto,   avcal,  avdat,  bdtr,   besi,   besj,   &
        bound,   cadd,           ccpy,   ccut,   cdtr,   cel1,   cel2,   chisq,  &
cint,   cnp,     cnps,   convt,  corre,  cross,  cs,     csp,    csps,   csrt,   &
csum,   ctab,    ctie,   dacfi,  dahi,   dali,   dapch,  dapfs,  dapll,  darat,  &
datse,  datsg,   datsm,  dbar,   dcar,   dcel1,  dcel2,  dcla,   dcnp,   dcnps,  &
dcpy,   dcsp,    dcsps,  ddbar,  ddcar,  ddet3,  ddet5,  ddgt3,  deli1,  deli2,  &
det3,   det5,    dfmcg,  dfmfp,  dfrat,  dgelb,  dgelg,  dgels,  dgt3,   dharm,  &
dhep,   dheps,   dhpcg,  dhpcl,  discr,  djelf,  dlap,   dlaps,  dlbvp,  dlep,   &
dleps,  dlgam,   dllsq,  dmatx,  dmchb,  dmfgr,  dmfsd,  dmfss,  dminv,  dmlss,  &
dmprc,  dmtds,   dpecn,  dpecs,  dpqfb,  dprbm,  dprqd,  dqa12,  dqa16,  dqa24,  &
dqa32,  dqa4,    dqa8,   dqatr,  dqg12,  dqg16,  dqg24,  dqg32,  dqg4,   dqg8,   &
dqh16,  dqh24,   dqh32,  dqh48,  dqh64,  dqh8,   dqhe,   dqhfe,  dqhfg,  dqhg,   &
dqhse,  dqhsg,   dql12,  dql16,  dql24,  dql32,  dql4,   dql8,   dqsf,   dqtfe,  &
dqtfg,  drharm,  drkgs,  drtmi,  drtni,  drtwi,  dse13,  dse15,  dse35,  dsg13,  &
dsinv,  dtcnp,   dtcsp,  dteas,  dteul,  dthep,  dtlap,  dtlep,  eigen,  eli1,   &
eli2,   expi,    exsmo,  factr,  fmcg,   fmfp,   forif,  forit,  frat,   gauss,  &
gdata,  gelb,    gelg,   gels,   gmadd,  gmmma,  gmprd,  gmsub,  gmtra,  gtprd,  &
harm,   hep,     heps,   hpcg,   hpcl,   hsbg,   inue,   i0,     jelf,   kolm2,  &
kolmo,  krank,   lap,    laps,   lbvp,   lep,    leps,   llsq,   load,   loc,    &
madd,   mata,    mchb,   mcpy,   meanq,  mfgr,   mfsd,   mfss,   mfun,   minv,   &
misr,   mlss,    momen,  mpair,  mprc,   mprd,   mstr,   msub,   mtds,   mtra,   &
multr,  ndtr,    ndtri,  nroot,  order,  padd,   paddm,  pcla,   pcld,   pder,   &
pdiv,   pecn,    pecs,   perm,   pgcd,   phi,    pild,   pint,   pmpy,   pnorm,  &
point,  polrt,   pprcn,  pqfb,   pqsd,   prbm,   probt,  prqd,   psub,   pval,   &
pvsub,  qa10,    qa2,    qa3,    qa4,    qa5,    qa6,    qa7,    qa8,    qa9,    &
qatr,   qg10,    qg2,    qg3,    qg4,    qg5,    qg6,    qg7,    qg8,    qg9,    &
qh10,   qh2,     qh3,    qh4,    qh5,    qh6,    qh7,    qh8,    qh9,    qhfe,   &
qhfg,   qhse,    qhsg,   ql10,   ql2,    ql3,    ql4,    ql5,    ql6,    ql7,    &
ql8,    ql9,     qsf,    qtest,  qtfe,   qtfg,   radd,   randu,  rank,   rcpy,   &
rcut,   recp,    rharm,  rint,   rk1,    rk2,    rkgs,   rslmc,  rsrt,   rsum,   &
rtab,   rtie,    rtmi,   rtni,   rtwi,   sadd,   scla,   scma,   sdiv,   se13,   &
se15,   se35,    sg13,   sici,   signt,  simq,   sinv,   smirn,  smo,    smpy,   &
srank,  srate,   srma,   ssub,   stprg,  submx,  subst,  tab1,   tab2,   tally,  &
tcnp,   tcsp,    teas,   tetra,  teul,   thep,   tie,    tlap,   tlep,   tprd,   &
trace,  ttest,   twoav,  utest,  varmx,  wtest,  xcpy
contains
include "absnt.finc"
include "acfi.finc"
include "ahi.finc"
include "ali.finc"
include "apch.finc"
include "apfs.finc"
include "apll.finc"
include "apmm.finc"
include "arat.finc"
include "array.finc"
include "ateig.finc"
include "atse.finc"
include "atsg.finc"
include "atsm.finc"
include "auto.finc"
include "avcal.finc"
include "avdat.finc"
include "bdtr.finc"
include "besi.finc"
include "besj.finc"
include "bound.finc"
include "cadd.finc"
include "ccpy.finc"
include "ccut.finc"
include "cdtr.finc"
include "cel1.finc"
include "cel2.finc"
include "chisq.finc"
include "cint.finc"
include "cnp.finc"
include "cnps.finc"
include "convt.finc"
include "corre.finc"
include "cross.finc"
include "cs.finc"
include "csp.finc"
include "csps.finc"
include "csrt.finc"
include "csum.finc"
include "ctab.finc"
include "ctie.finc"
include "dacfi.finc"
include "dahi.finc"
include "dali.finc"
include "dapch.finc"
include "dapfs.finc"
include "dapll.finc"
include "darat.finc"
include "datse.finc"
include "datsg.finc"
include "datsm.finc"
include "dbar.finc"
include "dcar.finc"
include "dcel1.finc"
include "dcel2.finc"
include "dcla.finc"
include "dcnp.finc"
include "dcnps.finc"
include "dcpy.finc"
include "dcsp.finc"
include "dcsps.finc"
include "ddbar.finc"
include "ddcar.finc"
include "ddet3.finc"
include "ddet5.finc"
include "ddgt3.finc"
include "deli1.finc"
include "deli2.finc"
include "det3.finc"
include "det5.finc"
include "dfmcg.finc"
include "dfmfp.finc"
include "dfrat.finc"
include "dgelb.finc"
include "dgelg.finc"
include "dgels.finc"
include "dgt3.finc"
include "dharm.finc"
include "dhep.finc"
include "dheps.finc"
include "dhpcg.finc"
include "dhpcl.finc"
include "discr.finc"
include "djelf.finc"
include "dlap.finc"
include "dlaps.finc"
include "dlbvp.finc"
include "dlep.finc"
include "dleps.finc"
include "dlgam.finc"
include "dllsq.finc"
include "dmatx.finc"
include "dmchb.finc"
include "dmfgr.finc"
include "dmfsd.finc"
include "dmfss.finc"
include "dminv.finc"
include "dmlss.finc"
include "dmprc.finc"
include "dmtds.finc"
include "dpecn.finc"
include "dpecs.finc"
include "dpqfb.finc"
include "dprbm.finc"
include "dprqd.finc"
include "dqa12.finc"
include "dqa16.finc"
include "dqa24.finc"
include "dqa32.finc"
include "dqa4.finc"
include "dqa8.finc"
include "dqatr.finc"
include "dqg12.finc"
include "dqg16.finc"
include "dqg24.finc"
include "dqg32.finc"
include "dqg4.finc"
include "dqg8.finc"
include "dqh16.finc"
include "dqh24.finc"
include "dqh32.finc"
include "dqh48.finc"
include "dqh64.finc"
include "dqh8.finc"
include "dqhe.finc"
include "dqhfe.finc"
include "dqhfg.finc"
include "dqhg.finc"
include "dqhse.finc"
include "dqhsg.finc"
include "dql12.finc"
include "dql16.finc"
include "dql24.finc"
include "dql32.finc"
include "dql4.finc"
include "dql8.finc"
include "dqsf.finc"
include "dqtfe.finc"
include "dqtfg.finc"
include "drharm.finc"
include "drkgs.finc"
include "drtmi.finc"
include "drtni.finc"
include "drtwi.finc"
include "dse13.finc"
include "dse15.finc"
include "dse35.finc"
include "dsg13.finc"
include "dsinv.finc"
include "dtcnp.finc"
include "dtcsp.finc"
include "dteas.finc"
include "dteul.finc"
include "dthep.finc"
include "dtlap.finc"
include "dtlep.finc"
include "eigen.finc"
include "eli1.finc"
include "eli2.finc"
include "expi.finc"
include "exsmo.finc"
include "factr.finc"
include "fmcg.finc"
include "fmfp.finc"
include "forif.finc"
include "forit.finc"
include "frat.finc"
include "gauss.finc"
include "gdata.finc"
include "gelb.finc"
include "gelg.finc"
include "gels.finc"
include "gmadd.finc"
include "gmmma.finc"
include "gmprd.finc"
include "gmsub.finc"
include "gmtra.finc"
include "gtprd.finc"
include "harm.finc"
include "hep.finc"
include "heps.finc"
include "hpcg.finc"
include "hpcl.finc"
include "hsbg.finc"
include "inue.finc"
include "i0.finc"
include "jelf.finc"
include "kolm2.finc"
include "kolmo.finc"
include "krank.finc"
include "lap.finc"
include "laps.finc"
include "lbvp.finc"
include "lep.finc"
include "leps.finc"
include "llsq.finc"
include "load.finc"
include "loc.finc"
include "madd.finc"
include "mata.finc"
include "mchb.finc"
include "mcpy.finc"
include "meanq.finc"
include "mfgr.finc"
include "mfsd.finc"
include "mfss.finc"
include "mfun.finc"
include "minv.finc"
include "misr.finc"
include "mlss.finc"
include "momen.finc"
include "mpair.finc"
include "mprc.finc"
include "mprd.finc"
include "mstr.finc"
include "msub.finc"
include "mtds.finc"
include "mtra.finc"
include "multr.finc"
include "ndtr.finc"
include "ndtri.finc"
include "nroot.finc"
include "order.finc"
include "padd.finc"
include "paddm.finc"
include "pcla.finc"
include "pcld.finc"
include "pder.finc"
include "pdiv.finc"
include "pecn.finc"
include "pecs.finc"
include "perm.finc"
include "pgcd.finc"
include "phi.finc"
include "pild.finc"
include "pint.finc"
include "pmpy.finc"
include "pnorm.finc"
include "point.finc"
include "polrt.finc"
include "pprcn.finc"
include "pqfb.finc"
include "pqsd.finc"
include "prbm.finc"
include "probt.finc"
include "prqd.finc"
include "psub.finc"
include "pval.finc"
include "pvsub.finc"
include "qa10.finc"
include "qa2.finc"
include "qa3.finc"
include "qa4.finc"
include "qa5.finc"
include "qa6.finc"
include "qa7.finc"
include "qa8.finc"
include "qa9.finc"
include "qatr.finc"
include "qg10.finc"
include "qg2.finc"
include "qg3.finc"
include "qg4.finc"
include "qg5.finc"
include "qg6.finc"
include "qg7.finc"
include "qg8.finc"
include "qg9.finc"
include "qh10.finc"
include "qh2.finc"
include "qh3.finc"
include "qh4.finc"
include "qh5.finc"
include "qh6.finc"
include "qh7.finc"
include "qh8.finc"
include "qh9.finc"
include "qhfe.finc"
include "qhfg.finc"
include "qhse.finc"
include "qhsg.finc"
include "ql10.finc"
include "ql2.finc"
include "ql3.finc"
include "ql4.finc"
include "ql5.finc"
include "ql6.finc"
include "ql7.finc"
include "ql8.finc"
include "ql9.finc"
include "qsf.finc"
include "qtest.finc"
include "qtfe.finc"
include "qtfg.finc"
include "radd.finc"
include "randu.finc"
include "rank.finc"
include "rcpy.finc"
include "rcut.finc"
include "recp.finc"
include "rharm.finc"
include "rint.finc"
include "rk1.finc"
include "rk2.finc"
include "rkgs.finc"
include "rslmc.finc"
include "rsrt.finc"
include "rsum.finc"
include "rtab.finc"
include "rtie.finc"
include "rtmi.finc"
include "rtni.finc"
include "rtwi.finc"
include "sadd.finc"
include "scla.finc"
include "scma.finc"
include "sdiv.finc"
include "se13.finc"
include "se15.finc"
include "se35.finc"
include "sg13.finc"
include "sici.finc"
include "signt.finc"
include "simq.finc"
include "sinv.finc"
include "smirn.finc"
include "smo.finc"
include "smpy.finc"
include "srank.finc"
include "srate.finc"
include "srma.finc"
include "ssub.finc"
include "stprg.finc"
include "submx.finc"
include "subst.finc"
include "tab1.finc"
include "tab2.finc"
include "tally.finc"
include "tcnp.finc"
include "tcsp.finc"
include "teas.finc"
include "tetra.finc"
include "teul.finc"
include "thep.finc"
include "tie.finc"
include "tlap.finc"
include "tlep.finc"
include "tprd.finc"
include "trace.finc"
include "ttest.finc"
include "twoav.finc"
include "utest.finc"
include "varmx.finc"
include "wtest.finc"
include "xcpy.finc"
!include "canor.finc"
!include "biser.finc"
!include "besk.finc"
!include "besy.finc"
!include "dapmm.finc"
end module Scientific_Subroutine_Package
